"""empty message

Revision ID: 17b15b0bdcfe
Revises: a7afb7f96312
Create Date: 2019-08-06 13:56:14.079084

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '17b15b0bdcfe'
down_revision = 'a7afb7f96312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('shadow_invigilator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'shadow_invigilator_id')
    # ### end Alembic commands ###
