"""empty message

Revision ID: aa5365620e10
Revises: cbf81e4d5757
Create Date: 2019-03-27 13:06:30.647887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5365620e10'
down_revision = 'cbf81e4d5757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_returned_date', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'exam_returned_date')
    # ### end Alembic commands ###
