"""empty message

Revision ID: e69353479750
Revises: dde147539d6e
Create Date: 2019-08-21 13:04:46.242287

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'e69353479750'
down_revision = 'dde147539d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_invigilator_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'invigilator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('invigilator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('booking_invigilator_id_fkey', 'booking', 'invigilator', ['invigilator_id'], ['invigilator_id'])
    # ### end Alembic commands ###
